"""empty message

Revision ID: f42e06de5e62
Revises: b81a7f1d36e4
Create Date: 2022-01-05 09:55:58.215875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f42e06de5e62'
down_revision = 'b81a7f1d36e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'looking_for_venues')
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('Venue', 'looking_for_talent')
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('shows', 'show_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('show_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    op.add_column('Venue', sa.Column('looking_for_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'seeking_talent')
    op.add_column('Artist', sa.Column('looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_venues')
    # ### end Alembic commands ###
